spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mock_project_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: root
    password: sa123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: anbui1435@gmail.com
    password: mryw jzak rhrg aiqb
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
  port: 8080

vnpay:
  tmnCode: PYRHRA8O
  hashSecret: T2HWSMBX62REMQHPNCAPUVT8HTG3ISCX
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/vnpay/return
  ipn-url: http://localhost:8080/api/vnpay/ipn

tmdb:
  api: 22dec769317e241940b4117c8fd359cc
  paste-url: http://api.themoviedb.org/3